name: Build image
description: Build Docker image
inputs:
  version:
    description: php version
    required: true
  platform:
    description: docker platform
    required: false
    default: linux/amd64
  workdir:
    description: dockerfile directory
    required: true
runs:
  using: "composite"
  steps:
  - name: Build image
    env:
      PHP_VERSION: ${{ inputs.version }}
      PLATFORM: ${{ inputs.platform }}
    run: |
      set -e
      $GITHUB_ACTION_PATH/release.sh
    shell: bash
    working-directory: ${{ inputs.workdir }}