name: Build and push docker images

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * 0'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  php83:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'docker'
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64
    - uses: docker/setup-buildx-action@v3
    - uses: ./.github/actions
      with:
        version: 8.3
        workdir: docker
        platform: linux/amd64,linux/arm64
  php82:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'docker'
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64
    - uses: docker/setup-buildx-action@v3
    - uses: ./.github/actions
      with:
        version: 8.2
        workdir: docker
        platform: linux/amd64,linux/arm64
  php81:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'docker'
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64
    - uses: docker/setup-buildx-action@v3
    - uses: ./.github/actions
      with:
        version: 8.1
        workdir: docker
        platform: linux/amd64,linux/arm64
  php80:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'docker'
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64
    - uses: docker/setup-buildx-action@v3
    - uses: ./.github/actions
      with:
        version: 8.0
        workdir: docker
        platform: linux/amd64,linux/arm64