name: build-and-push

on:
    workflow_dispatch:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Checkout
      uses: actions/checkout@main
    - name: Build and push images
      run: make build-and-push